services:
  Shop.Customer.infra.InMemoryCustomerRepository:
    class: ../../../../context/shop/customer/infra/persistence/InMemoryCustomerRepository

  Shop.Customer.application.CustomerCreator:
    class: ../../../../context/shop/customer/application/CustomerCreator
    arguments: ["@Shop.Customer.infra.InMemoryCustomerRepository"]

  Shop.Customer.application.CustomerFinder:
    class: ../../../../context/shop/customer/application/CustomerFinder
    arguments: ["@Shop.Customer.infra.InMemoryCustomerRepository"]

  Shop.Customer.application.CustomerRemover:
    class: ../../../../context/shop/customer/application/CustomerRemover
    arguments: ["@Shop.Customer.infra.InMemoryCustomerRepository"]

  Shop.Customer.application.CustomerUpdater:
    class: ../../../../context/shop/customer/application/CustomerUpdater
    arguments: ["@Shop.Customer.infra.InMemoryCustomerRepository"]
